#!/usr/bin/env bash

if [[ -f gear_config ]]; then
  BLACKBOX_TEST_SECRET_JSON="$(cat ./gear_config)" TEST_MODE=blackbox_local TEST_PORT=8080 PORT=8081 mix test
else
  echo "./gear_config file missing"
  exit 1
fi
